---
title: "README"
---

## Sentimental Words, Pronouns, and Genres

> Sentiment analysis has emerged to be a popular area to in analyzing social media discourse, with the publicization of various platforms. It classified sentimental expressions into five basic categories: *super positive, positive, super negative, negative and neutral*, drawing general conclusions on individuals' sentiments and their sentimental level in diverse posts. The same method can be employed to analyze other genres of writings, exploring sentimental levels and tendency in dissimilar genres. This study aims to find correlation among the use of pronounces and sentimental words and genres. Through employing methods of text analysis and sentiment analysis and comparing and contrasting uses of sentimental words and pronouns in different genres and results of analysis from each genre, the study is able to predict of the genre of the text, based on sentimental words and pronounces the text contained. 

## Reproduce

> Include a step-by-step guide to reproduce your project here. This should include a list of dependencies and instructions on how to run the project.
